[package]
name = "diesel-async"
version = "0.2.1"
authors = ["Georg Semmler <github@weiznich.de>"]
edition = "2018"
autotests = false
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/weiznich/diesel_async"
keywords = ["orm", "database", "sql", "async"]
categories = ["database"]
description = "An async extension for Diesel the safe, extensible ORM and Query Builder"
rust-version = "1.65.0"

[dependencies]
#diesel = { version = "~2.0.0", default-features = false, features = ["i-implement-a-third-party-backend-and-opt-into-breaking-changes"]}
diesel = { version = "~2.0.0", git = "https://github.com/neogenie/diesel.git", default-features = false, features = ["i-implement-a-third-party-backend-and-opt-into-breaking-changes"]}
async-trait = "0.1.66"
futures-channel = { version = "0.3.17", default-features = false, features = ["std", "sink"], optional = true }
futures-util = { version = "0.3.17", default-features = false, features = ["std", "sink"] }
tokio-postgres = { version = "0.7.2", optional = true}
tokio = { version = "1.26", optional = true}
mysql_async = { version = ">=0.30.0,<0.32", optional = true}
mysql_common = {version = "0.29.0", optional = true}

bb8 = {version = "0.8", optional = true}
deadpool = {version = "0.9", optional = true}
mobc = {version = ">=0.7,<0.9", optional = true}
scoped-futures = {version = "0.1", features = ["std"]}

[dev-dependencies]
tokio = {version = "1.12.0", features = ["rt", "macros", "rt-multi-thread"]}
cfg-if = "1"
chrono = "0.4"
diesel = { version = "~2.0.0", git = "https://github.com/neogenie/diesel.git", default-features = false, features = ["chrono"]}
#diesel = { version = "2.0.0", default-features = false,  features = ["chrono"]}

[features]
default = []
mysql = ["diesel/mysql_backend", "mysql_async", "mysql_common", "futures-channel"]
postgres = ["diesel/postgres_backend", "tokio-postgres", "tokio", "tokio/rt"]

[[test]]
name = "integration_tests"
path = "tests/lib.rs"
harness = true

[package.metadata.docs.rs]
features = ["postgres", "mysql", "deadpool", "bb8", "mobc"]
no-default-features = true
rustc-args = ["--cfg", "doc_cfg"]
rustdoc-args = ["--cfg", "doc_cfg"]

[patch.crates-io]
diesel = { git = "https://github.com/diesel-rs/diesel", rev = "b878fed" }
